<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Bloodmoon.json" />
    <None Remove="morrowind.json" />
    <None Remove="npc.json" />
    <None Remove="npc_AutoCalcOff.json" />
    <None Remove="TamrielRebuilt.json" />
    <None Remove="Tribunal.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="JSONReader\data\Bloodmoon.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="JSONReader\data\morrowind.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="JSONReader\data\npc.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="JSONReader\data\npc_AutoCalcOff.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="JSONReader\data\TamrielRebuilt.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="JSONReader\data\Tribunal.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
