UPDATE `npc` SET `Race`='Khajiit' WHERE `Race` IN ('T_Els_Suthay','T_Els_Ohmes-raht','T_Els_Cathay-raht','T_Els_Cathay','T_Els_Dagi-raht','T_Els_Ohmes');
UPDATE `npc` SET `Race`='Keptu' WHERE `Race`='T_Cnq_Keptu';
UPDATE `npc` SET `Race`='ChimeriQuey' WHERE `Race`='T_Cnq_ChimeriQuey';
UPDATE `npc` SET `Race`='Reachman' WHERE `Race`='T_Sky_Reachman';
UPDATE `npc` SET `Race`='Malahk Orc' WHERE `Race`='T_Mw_Malahk_Orc';
UPDATE `npc` SET `Race`='Imga' WHERE `Race`='T_Val_Imga';
UPDATE `npc` SET `Race`='Ynesai' WHERE `Race`='T_Yne_Ynesai';
UPDATE `npc` SET `Race`='Riverfolk' WHERE `Race`='T_Hr_Riverfolk';
UPDATE `npc` SET `Race`='Tsaesci' WHERE `Race`='T_Aka_Tsaesci';
UPDATE `npc` SET `Race`='Duadri' WHERE `Race`='T_Yok_Duadri';
UPDATE `npc` SET `Race`='Sea Elf' WHERE `Race`='T_Pya_SeaElf';

UPDATE `npc` SET `Faction`='Imperial Navy' WHERE `Faction` IN ('T_Mw_ImperialNavy', 'T_Cyr_ImperialNavy');
UPDATE `npc` SET `Faction`='Indoril' WHERE `Faction` = 'T_Mw_HouseIndoril';
UPDATE `npc` SET `Faction`='Archaeological Society' WHERE `Faction` = 'T_Glb_ArchaeologicalSociety';
UPDATE `npc` SET `Faction`='Dres' WHERE `Faction` = 'T_Mw_HouseDres';
UPDATE `npc` SET `Faction`='Syvvit Tong' WHERE `Faction` = 'TR_Fact_SyvvitTong';
UPDATE `npc` SET `Faction`='Clan Baluath' WHERE `Faction` = 'T_Mw_Clan_Baluath';
UPDATE `npc` SET `Faction`='Clan Orlukh' WHERE `Faction` = 'T_Mw_Clan_Orlukh';
UPDATE `npc` SET `Faction`='Courtesans Guild' WHERE `Faction` = 'T_Glb_CourtesansGuild';
UPDATE `npc` SET `Faction`='Shinathi' WHERE `Faction` = 'T_Mw_Shinathi';
UPDATE `npc` SET `Faction`='Ja Natta Syndicate' WHERE `Faction` = 'T_Mw_JaNattaSyndicate';
UPDATE `npc` SET `Faction`='Barristers Guild' WHERE `Faction` = 'T_Glb_BarristersGuild';
UPDATE `npc` SET `Faction`='Narsis Arena' WHERE `Faction` = 'TR_Fact_NarsisArena';
UPDATE `npc` SET `Faction`='Geographical Society' WHERE `Faction` = 'T_Glb_GeographicalSociety';
UPDATE `npc` SET `Faction`='Scenarists Guild' WHERE `Faction` = 'T_Glb_ScenaristsGuild';
UPDATE `npc` SET `Faction`='Astrological Society' WHERE `Faction` = 'T_Glb_AstrologicalSociety';
UPDATE `npc` SET `Faction`='Royal Haafingar Company' WHERE `Faction` = 'T_Sky_RoyalHaafingarCompany';
UPDATE `npc` SET `Faction`='Niben Hierophants' WHERE `Faction` = 'T_Cyr_NibenHierophants';
UPDATE `npc` SET `Faction`='Abecean Trading Company' WHERE `Faction` IN ('T_Cyr_AbeceanTradingCompany');
UPDATE `npc` SET `Faction`='Thieves Guild' WHERE `Faction` IN ('T_Cyr_ThievesGuild','T_Sky_ThievesGuild');
UPDATE `npc` SET `Faction`='Mages Guild' WHERE `Faction` IN ('T_Cyr_MagesGuild','T_Ham_MagesGuild','T_Sky_MagesGuild');
UPDATE `npc` SET `Faction`='Fighters Guild' WHERE `Faction` IN ('T_Cyr_FightersGuild','T_Sky_FightersGuild');
UPDATE `npc` SET `Faction`='Kingdom of Anvil' WHERE `Faction` = 'T_Cyr_KingdomAnvil';
UPDATE `npc` SET `Faction`='Imperial Legion' WHERE `Faction` IN ('T_Cyr_ImperialLegion','T_Sky_ImperialLegion');
UPDATE `npc` SET `Faction`='Imperial Cult' WHERE `Faction` IN ('T_Cyr_ImperialCult','T_Sky_ImperialCult');
UPDATE `npc` SET `Faction`='Fire Hand Clan' WHERE `Faction` = 'T_Sky_FireHandClan';
UPDATE `npc` SET `Faction`='Census And Excise' WHERE `Faction` = 'T_Cyr_CensusAndExcise';
UPDATE `npc` SET `Faction`='Kingdom of Reach' WHERE `Faction` = 'T_Sky_KingdomReach';
UPDATE `npc` SET `Faction`='Kingdom of Sutch' WHERE `Faction` = 'T_Cyr_KingdomSutch';
UPDATE `npc` SET `Faction`='Kingdom of Kvatch' WHERE `Faction` = 'T_Cyr_KingdomKvatch';
UPDATE `npc` SET `Faction`='Taliesinn' WHERE `Faction` = 'T_Sky_Taliesinn';
UPDATE `npc` SET `Faction`='Crowns' WHERE `Faction` = 'T_Ham_Crowns';
UPDATE `npc` SET `Faction`='Bear Clan' WHERE `Faction` = 'T_Sky_Bearclan';
UPDATE `npc` SET `Faction`='Alovach' WHERE `Faction` = 'T_Sky_Alovach';
UPDATE `npc` SET `Faction`='So-Mitana Company' WHERE `Faction` = 'T_Ham_So-MitanaCompany';
UPDATE `npc` SET `Faction`='Pachkan' WHERE `Faction` = 'T_Sky_Pachkan';
UPDATE `npc` SET `Faction`='Itinerant Priests' WHERE `Faction` = 'T_Cyr_ItinerantPriests';
UPDATE `npc` SET `Faction`='Ratcatchers Guild' WHERE `Faction` = 'T_Glb_RatcatchersGuild';
UPDATE `npc` SET `Faction`='Sogat Dur-Gada' WHERE `Faction` = 'T_Ham_SogatDurGada';
UPDATE `npc` SET `Faction`='Clan Khulari' WHERE `Faction` = 'T_Sky_ClanKhulari';
UPDATE `npc` SET `Faction`='Imperial Curia' WHERE `Faction` = 'T_Cyr_ImperialCuria';
UPDATE `npc` SET `Faction`='Hunnath' WHERE `Faction` = 'T_Sky_Hunnath';
UPDATE `npc` SET `Faction`='Braign' WHERE `Faction` = 'T_Sky_Braign';
UPDATE `npc` SET `Faction`='Dark Brotherhood' WHERE `Faction` IN ('T_Cyr_DarkBrotherhood','T_Sky_DarkBrotherhood');
UPDATE `npc` SET `Faction`='Ra-Habi Company' WHERE `Faction` = 'T_Ham_RaHabiCompany';
UPDATE `npc` SET `Faction`='Vampirum Order' WHERE `Faction` = 'T_Cyr_VampirumOrder';
UPDATE `npc` SET `Faction`='Blades' WHERE `Faction` = 'T_Cyr_Blades';

UPDATE `npc` SET `Faction`='None' WHERE `Faction` = '';

UPDATE `npc` SET `Class`='Alchemist' WHERE `Class` = 'Alchemist Service';
UPDATE `npc` SET `Class`='Apothecary' WHERE `Class` IN ( 'Apothecary Service' , 'T_Glb_ApothecaryService');
UPDATE `npc` SET `Class`='Assassin' WHERE `Class` = 'Assassin Service';
UPDATE `npc` SET `Class`='Battlemage' WHERE `Class` = 'Battlemage Service';
UPDATE `npc` SET `Class`='Drillmaster' WHERE `Class` = 'Drillmaster Service';
UPDATE `npc` SET `Class`='Enchanter' WHERE `Class` = 'Enchanter Service';
UPDATE `npc` SET `Class`='Healer' WHERE `Class` IN ('Healer Service','T_Glb_Healer');
UPDATE `npc` SET `Class`='Mage' WHERE `Class` = 'Mage Service';
UPDATE `npc` SET `Class`='Monk' WHERE `Class` = 'Monk Service';
UPDATE `npc` SET `Class`='Nightblade' WHERE `Class` = 'Nightblade Service';
UPDATE `npc` SET `Class`='Ordinator' WHERE `Class` = 'Ordinator Guard';
UPDATE `npc` SET `Class`='Priest' WHERE `Class` IN ('Priest Service','T_Glb_Priest');
UPDATE `npc` SET `Class`='Savant' WHERE `Class` IN ('Savant Service','T_Glb_Savant');
UPDATE `npc` SET `Class`='Sorcerer' WHERE `Class` = 'Sorcerer Service';
UPDATE `npc` SET `Class`='Thief' WHERE `Class` = 'Thief Service';
UPDATE `npc` SET `Class`='Trader' WHERE `Class` = 'Trader Service';
UPDATE `npc` SET `Class`='Artist' WHERE `Class` = 'T_Glb_Artist';
UPDATE `npc` SET `Class`='Astrologer' WHERE `Class` = 'T_Glb_Astrologer';
UPDATE `npc` SET `Class`='Baker' WHERE `Class` = 'T_Glb_Baker';
UPDATE `npc` SET `Class`='Banker' WHERE `Class` = 'T_Glb_Banker';
UPDATE `npc` SET `Class`='Barrister' WHERE `Class` = 'T_Glb_Barrister';
UPDATE `npc` SET `Class`='Broker' WHERE `Class` = 'T_Glb_Broker';
UPDATE `npc` SET `Class`='Carpenter' WHERE `Class` = 'T_Glb_Carpenter';
UPDATE `npc` SET `Class`='Cook' WHERE `Class` = 'T_Glb_Cook';
UPDATE `npc` SET `Class`='Courtesan' WHERE `Class` = 'T_Glb_Courtesan';
UPDATE `npc` SET `Class`='Dockworker' WHERE `Class` = 'T_Glb_Dockworker';
UPDATE `npc` SET `Class`='Fisherman' WHERE `Class` = 'T_Glb_Fisherman';
UPDATE `npc` SET `Class`='Fletcher' WHERE `Class` = 'T_Glb_Fletcher';
UPDATE `npc` SET `Class`='Jeweler' WHERE `Class` = 'T_Glb_Jeweler';
UPDATE `npc` SET `Class`='Lamp Knight' WHERE `Class` = 'T_Glb_Lampknight';
UPDATE `npc` SET `Class`='Miner' WHERE `Class` = 'T_Glb_Miner';
UPDATE `npc` SET `Class`='Naturalist' WHERE `Class` = 'T_Glb_Naturalist';
UPDATE `npc` SET `Class`='Potter' WHERE `Class` = 'T_Glb_Potter';
UPDATE `npc` SET `Class`='Ratcatcher' WHERE `Class` = 'T_Glb_Ratcatcher';
UPDATE `npc` SET `Class`='Sailor' WHERE `Class` = 'T_Glb_Sailor';
UPDATE `npc` SET `Class`='Scout' WHERE `Class` = 'T_Glb_Scout';
UPDATE `npc` SET `Class`='Scribe' WHERE `Class` = 'T_Glb_Scribe';
UPDATE `npc` SET `Class`='Trader' WHERE `Class` IN ('T_Glb_TraderService','T_Glb_Trader');
UPDATE `npc` SET `Class`='Cat Catcher' WHERE `Class` = 'T_Mw_CatCatcher';
UPDATE `npc` SET `Class`='Riverstrider' WHERE `Class` = 'T_Mw_RiverstriderService';
UPDATE `npc` SET `Class`='Bookseller' WHERE `Class` = 'T_Glb_Bookseller';
UPDATE `npc` SET `Class`='Publican' WHERE `Class` = 'T_Glb_Publican';
UPDATE `npc` SET `Class`='Commoner' WHERE `Class` = 'T_Glb_Commoner';
UPDATE `npc` SET `Class`='Pauper' WHERE `Class` = 'T_Glb_Pauper';
UPDATE `npc` SET `Class`='Clever-Man' WHERE `Class` ='T_Sky_Clever-Man';

UPDATE `npc` SET `Location`=`Region` WHERE `Location` = '';
UPDATE `npc` SET `Location`='None' WHERE `Location` = '';