CREATE TABLE `magiceffect` (
    `flags`            VARCHAR(255),
    `id`               VARCHAR(255),
    `name`             VARCHAR(255),
    `icon`             VARCHAR(255),
    `texture`          VARCHAR(255),
    `bolt_sound`       VARCHAR(255),
    `cast_sound`       VARCHAR(255),
    `hit_sound`        VARCHAR(255),
    `area_sound`       VARCHAR(255),
    `cast_visual`      VARCHAR(255),
    `bolt_visual`      VARCHAR(255),
    `hit_visual`       VARCHAR(255),
    `area_visual`      VARCHAR(255),
    `description`      TEXT,
    `expansion`        VARCHAR(255),
    `school`           VARCHAR(255),
    `base_cost`        DOUBLE,
    `data_flags`       VARCHAR(255),
    `color`            JSON,
    `speed`            DOUBLE,
    `size`             DOUBLE,
    `size_cap`         DOUBLE,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
