CREATE TABLE `creature` (
    `flags`                   VARCHAR(255),
    `id`                      VARCHAR(255),
    `name`                    VARCHAR(255),
    `mesh`                    VARCHAR(255),
    `Inventory`               JSON,
    `Spells`                  JSON,
    `Hello`                   INT,
    `Fight`                   INT,
    `Flee`                    INT,
    `Alarm`                   INT,
    `services`                VARCHAR(255),
    `creature_flags`          VARCHAR(255),
    `expansion`               VARCHAR(255),
    `creature_type`           VARCHAR(255),
    `level`                   INT,
    `strength`                INT,
    `intelligence`            INT,
    `willpower`               INT,
    `agility`                 INT,
    `speed`                   INT,
    `endurance`               INT,
    `personality`             INT,
    `luck`                    INT,
    `health`                  INT,
    `magicka`                 INT,
    `fatigue`                 INT,
    `soul`                    INT,
    `combat`                  INT,
    `magic`                   INT,
    `stealth`                 INT,
    `gold`                    INT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
