CREATE TABLE `weapon` (
    `flags`            VARCHAR(255),
    `id`               VARCHAR(255),
    `name`             VARCHAR(255),
    `mesh`             VARCHAR(255),
    `icon`             VARCHAR(255),
    `enchanting`       VARCHAR(255),
    `expansion`        VARCHAR(255),
    `weight`           DOUBLE,
    `value`            INT,
    `weapon_type`      VARCHAR(255),
    `health`           INT,
    `speed`            DOUBLE,
    `reach`            DOUBLE,
    `enchantment`      INT,
    `chop_min`         INT,
    `chop_max`         INT,
    `slash_min`        INT,
    `slash_max`        INT,
    `thrust_min`       INT,
    `thrust_max`       INT,
    `other`			   VARCHAR(255),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
