CREATE TABLE dialogueinfo (
    id                 VARCHAR(255),
    prev_id            VARCHAR(255),
    next_id            VARCHAR(255),
    speaker_id         VARCHAR(255) COLLATE "C",
    speaker_race       VARCHAR(255),
    speaker_class      VARCHAR(255),
    speaker_faction    VARCHAR(255),
    speaker_cell       VARCHAR(255),
    player_faction     VARCHAR(255),
    text               TEXT,
    expansion          VARCHAR(255),
    dialogue_topic     VARCHAR(255),
    dialogue_id        INTEGER,
    dialogue_type      VARCHAR(255),
    disposition        INTEGER,
    speaker_rank       INTEGER,
    speaker_sex        VARCHAR(255),
    player_rank        INTEGER,
    PRIMARY KEY (id)
);