CREATE TABLE creature (
    flags             VARCHAR(255),
    id                VARCHAR(255),
    name              VARCHAR(255),
    mesh              VARCHAR(255),
    inventory         JSONB,
    spells            JSONB,
    hello             INTEGER,
    fight             INTEGER,
    flee              INTEGER,
    alarm             INTEGER,
    services          VARCHAR(255),
    creature_flags    VARCHAR(255),
    expansion         VARCHAR(255),
    creature_type     VARCHAR(255),
    level             INTEGER,
    strength          INTEGER,
    intelligence      INTEGER,
    willpower         INTEGER,
    agility           INTEGER,
    speed             INTEGER,
    endurance         INTEGER,
    personality       INTEGER,
    luck              INTEGER,
    health            INTEGER,
    magicka           INTEGER,
    fatigue           INTEGER,
    soul              INTEGER,
    combat            INTEGER,
    magic             INTEGER,
    stealth           INTEGER,
    gold              INTEGER,
    PRIMARY KEY (id)
);