CREATE TABLE race (
    flags                 VARCHAR(255),
    id                    VARCHAR(255),
    name                  VARCHAR(255),
    spells                JSONB,
    description           TEXT,
    expansion             VARCHAR(255),
    skill_0               VARCHAR(255),
    bonus_0               INTEGER,
    skill_1               VARCHAR(255),
    bonus_1               INTEGER,
    skill_2               VARCHAR(255),
    bonus_2               INTEGER,
    skill_3               VARCHAR(255),
    bonus_3               INTEGER,
    skill_4               VARCHAR(255),
    bonus_4               INTEGER,
    skill_5               VARCHAR(255),
    bonus_5               INTEGER,
    skill_6               VARCHAR(255),
    bonus_6               INTEGER,
    male_strength         INTEGER,
    female_strength       INTEGER,
    male_intelligence     INTEGER,
    female_intelligence   INTEGER,
    male_willpower        INTEGER,
    female_willpower      INTEGER,
    male_agility          INTEGER,
    female_agility        INTEGER,
    male_speed            INTEGER,
    female_speed          INTEGER,
    male_endurance        INTEGER,
    female_endurance      INTEGER,
    male_personality      INTEGER,
    female_personality    INTEGER,
    male_luck             INTEGER,
    female_luck           INTEGER,
    male_height           DOUBLE PRECISION,
    female_height         DOUBLE PRECISION,
    male_weight           DOUBLE PRECISION,
    female_weight         DOUBLE PRECISION,
    data_flags            VARCHAR(255),
    PRIMARY KEY (id)
);