CREATE TABLE weapon (
    flags          VARCHAR(255),
    id             VARCHAR(255),
    name           VARCHAR(255),
    mesh           VARCHAR(255),
    icon           VARCHAR(255),
    enchanting     VARCHAR(255),
    expansion      VARCHAR(255),
    weight         DOUBLE PRECISION,
    value          INTEGER,
    weapon_type    VARCHAR(255),
    health         INTEGER,
    speed          DOUBLE PRECISION,
    reach          DOUBLE PRECISION,
    enchantment    INTEGER,
    chop_min       INTEGER,
    chop_max       INTEGER,
    slash_min      INTEGER,
    slash_max      INTEGER,
    thrust_min     INTEGER,
    thrust_max     INTEGER,
    data_flags     VARCHAR(255),
    PRIMARY KEY (id)
);