<?php

//FILTER CONSTANTS

const RACES = ['Imperial',
'Dark Elf',
'Wood Elf',
'High Elf',
'Breton',
'Duadri',
'Orc',
'Khajiit',
'Nord',
'Argonian',
'Redguard',
'Keptu',
'ChimeriQuey',
'Reachman',
'Malahk Orc',
'Imga',
'Ynesai',
'Riverfolk',
'Tsaesci',
'Sea Elf'];

const CLASSES = ['Acrobat',
'Agent',
'Alchemist',
'Apothecary',
'Archer',
'Artist',
'Assassin',
'Astrologer',
'Baker',
'Banker',
'Barbarian',
'Bard',
'Barrister',
'Battlemage',
'Bookseller',
'Broker',
'Buoyant Armiger',
'Caravaner',
'Caretaker',
'Carpenter',
'Cat Catcher',
'Champion',
'Clever-Man',
'Clothier',
'Commoner',
'Cook',
'Courtesan',
'Crusader',
'Dockworker',
'Dreamers',
'Drillmaster',
'Enchanter',
'Enforcer',
'Farmer',
'Fisherman',
'Fletcher',
'Gardener',
'Gondolier',
'Guard',
'Guild Guide',
'Healer',
'Herder',
'Hunter',
'Jeweler',
'Journalist',
'King',
'Knight',
'Lamp Knight',
'Mabrigash',
'Mage',
'Master-at-Arms',
'Merchant',
'Miner',
'Monk',
'Naturalist',
'Necromancer',
'Nightblade',
'Noble',
'Ordinator',
'Pauper',
'Pawnbroker',
'Pilgrim',
'Potter',
'Priest',
'Publican',
'Queen Mother',
'Ratcatcher',
'Riverstrider',
'Rogue',
'Sailor',
'Savant',
'Scout',
'Scribe',
'Shaman',
'Sharpshooter',
'Shipmaster',
'Slave',
'Smith',
'Smuggler',
'Sorcerer',
'Spellsword',
'Thief',
'Trader',
'Warlock',
'Warrior',
'Wise Woman',
'Witch',
'Witchhunter'
];

const FACTIONS = [
'Abecean Trading Company',
'Alovach',
'Archaeological Society',
'Ashlanders',
'Astrological Society',
'Barristers Guild',
'Bear Clan',
'Blades',
'Braign',
'Camonna Tong',
'Census and Excise',
'Clan Aundae',
'Clan Baluath',
'Clan Berne',
'Clan Khulari',
'Clan Orlukh',
'Clan Quarra',
'Courtesans Guild',
'Crowns',
'Dark Brotherhood',
'Dres',
'East Empire Company',
'Fighters Guild',
'Fire Hand Clan',
'Geographical Society',
'Hands of Almalexia',
'Hlaalu',
'Hunnath',
'Imperial Cult',
'Imperial Curia',
'Imperial Legion',
'Imperial Navy',
'Indoril',
'Itinerant Priests',
'Ja Natta Syndicate',
'Kingdom of Anvil',
'Kingdom of Kvatch',
'Kingdom of Reach',
'Kingdom of Sutch',
'Mages Guild',
'Morag Tong',
'Narsis Arena',
'Niben Hierophants',
'None',
'Pachkan',
'Ra-Habi Company',
'Ratcatchers Guild',
'Redoran',
'Royal Guard',
'Royal Haafingar Company',
'Scenarists Guild',
'Shinathi',
'Sixth House',
'Skaal',
'So-Mitana Company',
'Sogat Dur-Gada',
'Syvvit Tong',
'Taliesinn',
'Talos Cult',
'Telvanni',
'Temple',
'Thieves Guild',
'Twin Lamps',
'Vampirum Order'
];

const GENDERS = ['FEMALE','MALE'];

const EXPANSIONS = ['Bloodmoon',
'Morrowind',
'Project Cyrodiil',
'Skyrim Home of the Nords',
'Tamriel Rebuilt',
'Tribunal'];

const BASE_LOCATIONS = ['Abaelun Mine',
'Abanabi',
'Abebaal Egg Mine',
'Abernanit',
'Abinabi',
'Adanumuran',
'Addadshashanammu',
'Addamasartus',
'Ahallaraddon Egg Mine',
'Aharasaplit Camp',
'Aharnabi',
'Aharunartus',
'Ahemmusa Camp',
'Ahinipalit',
'Aidanat Camp',
'Ainat',
'Akulakhan\'s Chamber',
'Ald Daedroth',
'Ald Redaynia',
'Ald Sotha',
'Ald Velothi',
'Ald-ruhn',
'Alen Ancestral Tomb',
'Almurbalarammi',
'Alof\'s Farmhouse',
'Andasreth',
'Andrano Ancestral Tomb',
'Andrethi Ancestral Tomb',
'Ansi',
'Aralen Ancestral Tomb',
'Arano Plantation',
'Arenim Ancestral Tomb',
'Arkngthand',
'Arvel Manor',
'Arvel Plantation',
'Ascadian Isles Region',
'Asha-Ahhe Egg Mine',
'Ashalmawia',
'Ashalmimilkala',
'Ashamanu Camp',
'Ashanammu',
'Ashinabi',
'Ashir-Dan',
'Ashirbadon',
'Ashlands Region',
'Ashmelech',
'Ashunartes',
'Ashurnibibi',
'Assalkushalit',
'Assarnatamat',
'Assarnud',
'Assemanu',
'Assernerairan',
'Assu',
'Assumanu',
'Assurdirapal',
'Assurnabitashpi',
'Azura\'s Coast Region',
'Baan Urlai',
'Bahrund',
'Bal Fell',
'Bal Isra',
'Bal Ur',
'Balmora',
'Baram Ancestral Tomb',
'Bensiberib Camp',
'Beran Ancestral Tomb',
'Berandas',
'Beshara',
'Big Head\'s Shack',
'Bitter Coast Region',
'Bthuand',
'Buckmoth Legion Fort',
'Caldera',
'Caldera Mine',
'Cavern of the Incarnate',
'Chun-Ook',
'Clutter Warehouse - Everything Must Go!',
'Corprusarium',
'Corprusarium Bowels',
'Dagon Fel',
'Dagoth Ur',
'Dissapla Mine',
'Dralas Ancestral Tomb',
'Dren Plantation',
'Drethan Ancestral Tomb',
'Druscashti',
'Dubdilla',
'Dun-Ahhe',
'Dunada-Nammu',
'Dunirai Caverns',
'Dushariran',
'Ebernanit',
'Ebonheart',
'Elanius Camp',
'Elith-Pal Mine',
'Eluba-Addon Egg Mine',
'Endusal',
'Erabenimsun Camp',
'Esutanamus',
'Falasmaryon',
'Falensarano',
'Favel Ancestral Tomb',
'Galom Daeus',
'Ghostgate',
'Gimothran Ancestral Tomb',
'Ginith Ancestral Tomb',
'Gnaar Mok',
'Gnisis',
'Grazelands Region',
'Gro-Bagrat Plantation',
'Grytewake',
'Habinbaes',
'Halit Mine',
'Hanud',
'Hassour',
'Hawia Egg Mine',
'Hinnabi',
'Hla Oad',
'Hlormaren',
'Holamayan Monastery',
'Ibar-Dad',
'Ibishammus',
'Ihinipalit',
'Ilunibi',
'Imperial Prison Ship',
'Indaren Ancestral Tomb',
'Indarys Manor',
'Indoranyon',
'Kaushtababi Camp',
'Kaushtarari',
'Kemel-Ze',
'Khartag Point',
'Khuul',
'Koal Cave',
'Koal Cave Entrance',
'Kogoruhn',
'Kudanat',
'Kumarahaz',
'Kunirai',
'Kushtashpi',
'Llirala\'s Shack',
'Maar Gan',
'Maba-Ilu',
'Mababi',
'Maelkashishi',
'Maesa-Shammus Egg Mine',
'Mallapi',
'Mamaea',
'Mamshar-Disamus Camp',
'Mannammu',
'Marandus',
'Maren Ancestral Tomb',
'Massahanud Camp',
'Masseranit',
'Mat',
'Matus-Akin Egg Mine',
'Mawia',
'Mila-Nipal',
'Milk',
'Minabi',
'Ministry of Truth',
'Missamsi',
'Molag Mar',
'Molag Mar Region',
'Moonmoth Legion Fort',
'Morvayn Manor',
'Mournhold',
'Mzuleft',
'Nallit',
'Nammu',
'Nchuleftingth',
'Nchurdamz',
'Nerano Ancestral Tomb',
'Nissintu',
'Nund',
'Odai Plateau',
'Odaishah',
'Odibaal',
'Odirnamat',
'Odirniran',
'Odrosal',
'Omani Manor',
'Onnissiralis',
'Palansour',
'Panabanit-Nimawia Egg Mine',
'Panat',
'Panud Egg Mine',
'Pelagiad',
'Piernette\'s Farmhouse',
'Pinsun',
'Prelude Shipwreck',
'Pulk',
'Punabi',
'Punammu',
'Punsabanit',
'Ramimilk',
'Ravel Ancestral Tomb',
'Raviro Ancestral Tomb',
'Rayna Drolan\'s Shack',
'Red Mountain Region',
'Reloth Ancestral Tomb',
'Rethan Manor',
'Rissun',
'Rothan Ancestral Tomb',
'Rotheran',
'Sadrith Mora',
'Sadryon Ancestral Tomb',
'Salit Camp',
'Salvel Ancestral Tomb',
'Sanabi',
'Sanit',
'Sanni',
'Sarethi Ancestral Tomb',
'Sargon',
'Saturan',
'Serano Ancestral Tomb',
'Seyda Neen',
'Sha-Adnius',
'Shal',
'Shallit',
'Shara',
'Shashmanu Camp',
'Shashpilamat',
'Shashurari Camp',
'Sheogorad',
'Shishara',
'Shishi',
'Shulk Egg Mine',
'Shurinbaal',
'Shushan',
'Shushishi',
'Sinamusa Egg Mine',
'Sinsibadon',
'Sirrilash',
'Sirsadrorran',
'Sobitbael Camp',
'Sterdecan\'s Farmhouse',
'Sud',
'Sudanit Mine',
'Sulipund',
'Suran',
'Surirulk',
'Tel Aruhn',
'Tel Branora',
'Tel Mora',
'Tel Uvirith',
'Tel Vos',
'Telasero',
'Telvayn Ancestral Tomb',
'Tin-Ahhe',
'ToddTest',
'Tower of Tel Fyr',
'Tur Julan',
'Tureynulal',
'Tusenend',
'Ularradallaku',
'Ules Manor',
'Ulummusa',
'Urshilaku Camp',
'Uvirith\'s Grave',
'Valenvaryon',
'Vas',
'Venim Ancestral Tomb',
'Veramus Mine',
'Vivec',
'Vos',
'West Gash Region',
'Wolverine Hall',
'Wraithspire',
'Yakanalit',
'Yakaridan Camp',
'Yakin',
'Yamandalkal',
'Yanemus Mine',
'Yansirramus',
'Yasammidan',
'Yasamsi',
'Yassu Mine',
'Yesamsi',
'Zainab Camp',
'Zainsipilu',
'Zaintirari',
'Zaintiraris',
'Zanabi',
'Zebabi',
'Zenarbael',
'Zergonipal',];

const BLOODMOON_LOCATIONS = ['Ald-ruhn',
'Felsaad Coast Region',
'Fort Frostmoth',
'Hirstaang Forest Region',
'Isinfier Plains Region',
'Khuul',
'Mark\'s Script Testing Cell',
'Raven Rock',
'Skaal Village',
'Solstheim',
'Thirsk'];

const TRIBUNAL_LOCATIONS = ['Ebonheart',
'Mournhold',
'Mournhold Temple: Basement',
'Mournhold Temple: Hall of Ministry',
'Mournhold Temple: High Chapel',
'Mournhold Temple: Infirmary',
'Mournhold Temple: Office of the Lord Archcanon',
'Mournhold Temple: Reception Area',
'Old Mournhold: Bazaar Sewers',
'Old Mournhold: Forgotten Sewer',
'Old Mournhold: Moril Manor',
'Old Mournhold: Residential Sewers',
'Old Mournhold: Temple Sewers East',
'Old Mournhold: Temple Sewers West',
'Old Mournhold: Teran Hall',
'Old Mournhold: West Sewers'];

const TAMRIEL_LOCATIONS = ['Aalmu Ouradas\' Shack',
'Aanthirin Region',
'Abaalalk Manammu\'s Dwelling',
'Acre of Saint Meris',
'Adadpaliki',
'Adammuburtu',
'Adammurbael',
'Adavrin Egg Mine',
'Adavrin Plantation',
'Addai Mine',
'Addai-Marananit Tunnel',
'Adhuhartis',
'Adunji',
'Adursaranit',
'Aegondo Point',
'Age of Peace',
'Aharnat',
'Ahhepu',
'Ahhesha',
'Aimrah',
'Akamora',
'Alayepi\'s Tent',
'Ald Balaal',
'Ald Iuval',
'Ald Khan',
'Ald Marak',
'Ald Mirathi',
'Ald Niripal',
'Ald Uman',
'Ald Uran',
'Ald Verya',
'Ald Virak',
'Ald Volos',
'Alendu Plantation',
'Almas Thirr',
'Alnadribi',
'Alt Bosara',
'Alt Orethan Region',
'Alta Vathor',
'Alumawia',
'Alver Farmhouse',
'Ammar',
'Amthuandz',
'Amthuandz Excavations',
'Anashbibi',
'Anbarsud',
'Andar Mok',
'Andarannipal',
'Andrani Farmhouse',
'Antirrhinum: Cabin',
'Antirrhinum: Hold',
'Archtumz',
'Aren Farmhouse',
'Arkgnthleft',
'Armun Ashlands Region',
'Armun Pass Outpost',
'Arvel Ancestral Tomb',
'Arvs-Nalor',
'Arvs-Shadan',
'Arvud',
'Ashamul',
'Ashir-Ahat',
'Ashishibishi',
'Ashpibishal',
'Ashurbalipal',
'Ashushushi',
'Assinad',
'Assukilunend',
'Assurbalhet',
'Astius Claenia\'s Hideout',
'Asurnabi',
'Athemiran Cave Dwelling',
'Azurranu',
'Baelkashpitu',
'Bahrammu',
'Bahrund',
'Bal Dushal',
'Bal Foyen',
'Bal Oyra',
'Balathren',
'Baldrahn',
'Balititashpi',
'Balk Grotto',
'Balur Cave Dwelling',
'Banathi',
'Bapatipi',
'Barathmuk gro-Bagrat\'s shack',
'Barendreth',
'Barunal',
'Baryon Plantation',
'Basan-Dur',
'Basarnud',
'Bassuranu',
'Bazak',
'Bedulassadan',
'Belsabi Egg Mine',
'Bera Famori\'s Shack',
'Berantus',
'Bessarnamidan',
'Bin-Shual Egg Mine',
'Binammu',
'Bisandryon',
'Bitter Coast Region',
'Bodrum',
'Boethiah\'s Spine Region',
'Bosmora',
'Brave Coda',
'Brazen Maiden: Lower Level',
'Brazen Maiden: Upper Level',
'Bthangthamuzand',
'Bthuangthuv',
'Bthungtch',
'Bthzundcheft',
'Burraburiash',
'Calaril Comet',
'Casimor',
'Chenud',
'Chunzefk',
'Clambering Moor Region',
'Crab Knight',
'Crumbling Hut',
'Dadrys Ancestral Tomb',
'Daelkhun',
'Dagon Fel',
'Dagon Urul Region',
'Dagorda Cavern',
'Dansudipat Egg Mine',
'Dappled Dreugh',
'Daravel Ancestral Tomb',
'Darvonis',
'Dassur-Kur Lookout',
'Decodorius Ranch',
'Deep Waters',
'Delethren Cave Dwelling',
'Delos Deralin\'s House',
'Delvarrapal Cave Dwelling',
'Denaven Egg Mine',
'Denaven Egg Mine Housing',
'Denaven Manor',
'Denaven-Duladdon Egg Mine',
'Denaven-Zerabu Egg Mine',
'Diligent Faith',
'Dilitan Mine',
'Dim-Dai',
'Dinagimusa',
'Dondril',
'Dorammu Cavern',
'Dothril Ancestral Tomb',
'Dralnabissit',
'Drals Farmhouse',
'Dread Minotaur',
'Drenka Cavern',
'Dreynim',
'Dreynim Spa',
'Drothril Ancestral Tomb',
'Dubshal Hive',
'Duda',
'Dulandos',
'Dulun Varethi\'s Shack',
'Dun Akafell',
'Dun Akafell Canals',
'Dungra',
'Dunusi',
'Dusara',
'Dusura',
'Dutanat\'s Tent',
'Ebamasharisus',
'Ebamusharisus',
'Ebon Tower',
'Ebonheart',
'Ebunammidan',
'Edalvel Plantation',
'Edhryn Farothran\'s Lighthouse',
'Ehameshulk',
'Elfmaid: Cabin',
'Elfmaid: Hold',
'Elvul Farm',
'Emmurbalpitu',
'Enamor Dayn',
'Enar Sothran\'s Shack',
'Endelius\' Shack',
'Enravel Egg Mine',
'Eravan',
'Erda\'s Shack',
'Erelis Ilnim\'s Cave',
'Erethan Plantation',
'Ernabapalit Camp',
'Ernaberinsu',
'Ervas Dalveni\'s Shack',
'Essarnartes',
'Essurdan Cave Dwelling',
'Essurnashpi',
'Esuranamit',
'Etana Egg Mine',
'Eternal Voyager: Upper Level',
'Etu-Saras Egg Mine',
'Evos',
'Exodus',
'Exposed Shipwreck',
'Falascu',
'Felms Ithul',
'Firemoth Legion Fort',
'Firewatch',
'Fort Ancylis',
'Fort Umbermoth',
'Gah Sadrith',
'Galisa\'s Pike',
'Galseah',
'Gan-Ettu Camp',
'Garvs and Fedura Ovav\'s Shack',
'Gathram Farmhouse',
'Geras Egg Mine',
'Ghalud',
'Ghand',
'Ghundabalit Egg Mine',
'Git',
'Glass Fulcrum',
'Glinting Moth: Cabin',
'Glinting Moth: Crew Quarters',
'Gol Mok',
'Gorne',
'Gra-Bashamd Farm',
'Grand Hlaalu Ancestral Tomb',
'Gratitude\'s Wake',
'Grey-Walker',
'Gro-Uthig Plantation',
'Gulmebi',
'Gulmon Nulen\'s Hut',
'Gurilo Farmhouse',
'Habunsanit',
'Hadipasu',
'Hadrumnibibi',
'Halaran Camp',
'Haliwaran',
'Haniridun',
'Hannit',
'Harethim Manor',
'Harru Cavern',
'Harrumat Mine',
'Harsusirpal',
'Hasarund',
'Hassat-Nirram Egg Mine',
'Helnim',
'Helseri Farmhouse',
'Helval Ancestral Tomb',
'Helvi Ancestral Tomb',
'Herothran Egg Mine',
'Hjotir\'s Rock House',
'Hla Bulor',
'Hlaalu Egg Mine',
'Hlaanis',
'Hladri Winery',
'Hlan Oek',
'Hlermu',
'Hlersis',
'Hlerynhul',
'Hlorandar',
'Hlorandus',
'Hlorgir Firm-Hand\'s Shack',
'Hummurushtapi',
'Hunted Hound Inn',
'Hunza Camp',
'Ibbi-Suen Mine',
'Ibdali-Shipsi Egg Mine',
'Ibiammusashan',
'Ibinai',
'Idathren',
'Iden',
'Idrerayna Andalor\'s Shack',
'Ihnammoth',
'Ikinammassu',
'Illutu',
'Ilnakubi',
'Ilnibu',
'Ilu-Shuma Egg Mine',
'Ilvi Mine',
'Indal-ruhn',
'Indalas Ancestral Tomb',
'Inuibbisa',
'Ishal-Mul Egg Mine',
'Ishanuran Camp',
'Ishi-Dur',
'Issarbaddon',
'Issurnawia',
'Jaran\'s Shack',
'Jherun Egg Mine',
'Kadanuran',
'Kainat',
'Kaladryon',
'Kalishlapal',
'Kalkusara',
'Kannidamarus',
'Kapid-Namisat Egg Mine',
'Kassapu',
'Kaushaspi Egg Mine',
'Kaushirimilk',
'Kellidan',
'Kemel-Ze',
'Khalaan',
'Khalammu Grotto',
'Khirakai',
'Kirmunad',
'Koranyon',
'Kulemund',
'Kulidon',
'Kunashpat',
'Kunenillit',
'Kunenillit Camp',
'Kurhu',
'Kuriki',
'Kushrendar',
'Lagat gra-Lumbak\'s Shack',
'Lagryn Darys\' Shack',
'Lan Orethan Outpost',
'Lan Orethan Region',
'Lanasa Vidanes\' Shack',
'Landoth Ancestral Tomb',
'Llaram Plantation',
'Llaran Farm',
'Llarethi Ancestral Tomb',
'Llemis Ranch',
'Llendu Ancestral Tomb',
'Lleris Dalmar\'s Hideout',
'Llethnen Indri\'s Shack',
'Lloram Ancestral Tomb',
'Llothanis',
'Loen Doldal\'s Shack',
'Looted Shipwreck',
'Lukhalutun',
'Lumber Camp Overseer\'s Shack',
'Maar-Bani Crossing',
'Maarawat',
'Maatumassu',
'Mabit Grotto',
'Madalvel Ancestral Tomb',
'Maebbu',
'Maesanammus Mine',
'Mala Tor',
'Malamali',
'Malanibi Grotto',
'Malawius Camp',
'Malkamalit',
'Manamsi',
'Mandaran',
'Mannu',
'Mannusudipat Mine',
'Manrizache',
'Mansit-Nur Hive',
'Mansurabi',
'Mansutarmus',
'Mantassa Camp',
'Mar-Oniba Lookout',
'Marananit',
'Marisanibal',
'Marog',
'Marwat',
'Marys Cave Dwelling',
'Mashadananit',
'Mashanuad',
'Massanud',
'Massaunus',
'Massunat Mine',
'Mavandes Caravanserai',
'Mawapi-Addon',
'Mazkun',
'Melethi Lighthouse',
'Menaan',
'Mephalan Vales Region',
'Meralag',
'Merihayan',
'Midannecne',
'Mirou Grotto',
'Misapit',
'Molag Ruhn Region',
'Molagreahd Region',
'Molkobal',
'Monastery of St. Aralor',
'Monastery of St. Delyn',
'Monastery of St. Felms',
'Moraib',
'Morvil Arelath\'s Shack',
'Mothran Plantation',
'Mount Annu',
'Mount Dunul',
'Mount Sarrunabi',
'Mugan Crypt',
'Muld',
'Munat Egg Mine',
'Mundrethi Plantation',
'Mvelthngth-Schel',
'Mzungleft',
'Naarshamsi',
'Nadin Mine',
'Naemunbatashpi',
'Nalad',
'Nalmunabi',
'Namartyon',
'Namidan Egg Mine',
'Nandiryon Ancestral Tomb',
'Napali',
'Narael Lookout',
'Naram-Sin',
'Narcolepsy',
'Narsis',
'Narus River Camp',
'Nasinammu',
'Nassudan',
'Nassurdanami',
'Nav Andaram',
'Nchazdrumn',
'Nchulark',
'Nchulegfth',
'Nebulud',
'Necrom',
'Nedothril Region',
'Neleni-Shalsar Egg Mine',
'Nerebys Mine',
'Nethil Farmhouse',
'Nethre-Pulu',
'Nethre-Pulu Egg Mine',
'Nethril Plantation',
'Ngelfltingth',
'Nibabi',
'Niben\'s Wind: Cabin',
'Niben\'s Wind: Hold',
'Nim',
'Ninnimilk',
'Ninurtamul',
'Nirthfly: Lower Level',
'Nirthfly: Upper Level',
'Nissut Mine',
'Nivalis',
'Norem',
'Northern Wind: Cabin',
'Northern Wind: Hold',
'Num-Ittu Mine',
'Number Rooms Temple',
'Nunalabbi',
'Nurgal',
'Nurshadit',
'Obainat Camp',
'Odirnamus',
'Ogroth',
'Ohishiran',
'Old Dren Plantation',
'Old Ebonheart',
'Omathi Ancestral Tomb',
'Omaynis',
'Onimushili',
'Oran Plantation',
'Orelu Ancestral Tomb',
'Orelu Plantation',
'Osotla',
'Ossurnashalit',
'Othmura',
'Othrano',
'Othreleth Woods Region',
'Otori',
'Padomaic Ocean Region',
'Pahunsabi',
'Palamat Mine',
'Palisnabat',
'Pamonibu Mine',
'Pansaranit',
'Panshurra',
'Panudanit',
'Paruddma',
'Paruddma\'s Maw',
'Passur-Sur Lookout',
'Pedivur\'s Tower',
'Peninsula of Veloth',
'Pilnusibi Egg Mine',
'Pimmu',
'Piransulit',
'Plundered Shack',
'Port Telvannis',
'Pride of Narusia: Cabin',
'Pride of Narusia: Lower Deck',
'Pride of Narusia: Upper Deck',
'Pryai Bridge Outpost',
'Pryai-Nur Egg Mine',
'Pulu-Asha Egg Mine',
'Puman',
'Punudir Lookout',
'Puramindi',
'Puzur-Attin Egg Mine',
'Pyr-Ilu Lookout',
'Quadrille',
'Raal Grotto',
'Raathim Ancestral Tomb',
'Rabawia Grotto',
'Ralit Egg Mine',
'Rallabala',
'Ramaniran',
'Rangirth Ancestral Tomb',
'Ranis Arthyn\'s House',
'Ranyon-ruhn',
'Raran Ancestral Tomb',
'Rasdamassilu',
'Ratharzak',
'Ravalas Cavern',
'Relas Shack',
'Rethil Farm',
'Rilramisnat',
'Rilsoan',
'Rivenwake',
'Riverkeep',
'Rivul Farmhouse',
'Roa Dyr',
'Robed Warden',
'Romavel Ancestral Tomb',
'Romayon',
'Romithren Monastery',
'Rorissud',
'Roth Roryn Region',
'Runat',
'Rurvyn Egg Mine',
'Sacred Lands Region',
'Sacred Lands Sanctuary',
'Sad',
'Sadalvel Ancestral Tomb',
'Sadas Plantation',
'Sadavel Plantation',
'Sadrathim',
'Sadratus',
'Sadrith Mora',
'Sael-Hla',
'Sagea',
'Sailen',
'Salandus',
'Salavel Cave Dwelling',
'Salka Cave',
'Salvu Manor',
'Samapwi',
'Samori Farmhouse',
'Samursi',
'Sanammasour',
'Sannisaran Egg Mine',
'Sarahu',
'Sarat-Libali',
'Sarbiri',
'Sarmabael',
'Saros Mine',
'Sarvanni',
'Sarvanni Mole Crab Farm',
'Sasamsi Egg Mine',
'Sassanibat\'s Yurt',
'Sassur-Dari Mine',
'Satunabi',
'Saveri',
'Savrethi Distillery',
'Sea of Ghosts Region',
'Sebarmul',
'Seherbal Camp',
'Sehutu',
'Seitur',
'Selal Grotto',
'Selanasteris',
'Seles Ranch',
'Selyn',
'Septim\'s Gate Pass',
'Seranassid',
'Serasith Cavern',
'Serim Derthi\'s Shack',
'Seris',
'Serrudan',
'Serynthul',
'Sevadartus',
'Sevil Ancestral Tomb',
'Seyda Neen',
'Sha-Sudiran',
'Shaamishalk Cave Dwelling',
'Shaden',
'Shalmurat',
'Shambalu',
'Shamsi',
'Shan-Ahhe',
'Shashmassadan',
'Shipal-Sharai',
'Shipal-Shin Region',
'Shirel',
'Shul',
'Shularon',
'Shulun Harrinat: Trader',
'Shumalkashudanit',
'Shutaddipal: Shrine',
'Sihiltu Hive',
'Silkun-Tirlo Egg Mine',
'Silvin\'s Shack',
'Sinramen Monastery',
'Sinsi',
'Sirrilash',
'Sirsadrorran',
'Skaarling Queen: Hold',
'Sobbitana Grotto',
'Sobhidaz',
'Sodri-Tilur Egg Mine',
'Soludanni Egg Mine',
'Soramil and Rothera Galdavo\'s House',
'Soudi',
'St. Ino\'s Caravanserai',
'Stalled Shipwreck',
'Stormgate Pass',
'Suldun Egg Mine',
'Suldunanit',
'Sulfurwatch Keep',
'Sulindon',
'Sunad Mora Lighthouse',
'Sunat',
'Sundered Scar Region',
'Suraritu',
'Surathi Cave Dwelling',
'Surimintu',
'Surol Suth\'s Shack',
'Surpu',
'Syndros',
'Tabiash Egg Mine',
'Tahvel',
'Tananta',
'Tansumiran',
'Teknilashashulpi',
'Tel Aranyon',
'Tel Drevis',
'Tel Gilan',
'Tel Mothrivra',
'Tel Muthada',
'Tel Oren',
'Tel Ouada',
'Tel Rivus',
'Telomas Ancestral Tomb',
'Teloseras',
'Telvan Grotto',
'Telvanni Isles Region',
'Telvanni Waystation',
'TEM Ashrunner',
'TEM Ghostrunner',
'TEM Princess Morgiah: Cabin',
'TEM Princess Morgiah: Hold',
'TEM Saber of the Straits: Cabin',
'TEM Saber of the Straits: Hold',
'Terendas Mine',
'Teyn',
'Thalotheran Manor',
'Thalotheran Quarry',
'Tharonen Manor',
'Thavas Farm',
'The Grey Lodge',
'The Inn Between',
'The Space Gone Missing',
'Thirith Farm',
'Thirr Valley Region',
'Thirrine Lily',
'Tilmeth Manor',
'Tilvur Ancestral Tomb',
'Tiranshiha',
'Tirigan Camp',
'Tirilathran',
'Tiriramannu',
'Tomaril Manor',
'Tower of Tel Mothrivra',
'Tremelanit',
'Tristin',
'TR_HOLD_Firewatch Ext Merchants',
'TR_HOLD_Necrom Lighthouse',
'TR_HOLD_Silver Serpent',
'TR_HOLD_The Wayfarer: Cabin',
'TR_HOLD_The Wayfarer: Upper Level',
'Turendas',
'Turesa Veldyn\'s Tent',
'Udai',
'Udanasit',
'Uddanu',
'Uddunapsit',
'Ulanababia',
'Ulannanit Cave Dwelling',
'Ules Ancestral Tomb',
'Ulven Plantation',
'Ulyn Manor',
'Umalor Plantation',
'Uman',
'Unknown Grotto',
'Urnuridun Camp',
'Urussabi',
'Ushaninmis',
'Ushu-Kur',
'Ushu-Kur Mine',
'Ushudartus',
'Ussiran Camp',
'Uttumilk',
'Uvayn Ancestral Tomb',
'Vadaryn Plantation',
'Valsi Farmhouse',
'Valubi',
'Vandasir Egg Mine',
'Vandirelyon',
'Vantus Mine',
'Vantus Mine: Packing Room',
'Varashimmus',
'Varethan Mine',
'Vartalit Grotto',
'Vassadudas Mine',
'Vathras Plantation',
'Vedas Egg Mine',
'Vedas Plantation',
'Vedrano Farmhouse',
'Velk Camp',
'Velonith',
'Velothi Mountains Region',
'Veniroth Ancestral Tomb',
'Venymlan Deeps',
'Veralan Farm',
'Veralan Farmhouse',
'Veramus Mine',
'Veran Cave Dwelling',
'Verano Farmhouse',
'Veranzaris',
'Verdunasha-Beracavada Egg Mine',
'Verenabi',
'Verulas Pass',
'Vesi-Dur Grotto',
'Vhul',
'Viake Ancestral Tomb',
'Virdad',
'Viri Ranch',
'Virian Farm',
'Vivec',
'Vlars Manor',
'Volenfaryon',
'Vorus Odathil\'s House',
'Vounoura',
'Vul',
'Vulunith Ancestral Tomb',
'Vynbant',
'Vyr-Moran Lookout',
'Vys-Assanud',
'Vys-Ishra Lookout',
'Wavebreaker Keep',
'Web of Air',
'Whispered Tenet',
'Windbreaker Keep',
'Windbreaker Keep Inner Ruins',
'Windmoth Legion Fort',
'Wraithspire',
'Yabananit',
'Yadamsi',
'Yamandalkal',
'Yamniban',
'Yamuninisharn',
'Yan-Mael\'s Tent',
'Yanashpi',
'Yandaran',
'Yanimmu Mine',
'Yanishanabi',
'Yansumanmus Mine',
'Yashazmus',
'Yaztaramz',
'Yenashpi',
'Yenidan',
'Yennakiblis Camp',
'Yfrac Farmhouse',
'Yrgjol Steelfist\'s Shack',
'Zabamallit',
'Zainna',
'Zalitalan',
'Zanammu',
'Zarathil',
'Zatamushi',
'Zeddan',
'Zernital',
'Zirconia',
'Zuldassur Manor',
'Zunawi Egg Mine',
'Zurindi Grotto'];

const CYRODIIL_LOCATIONS = [
'Abecean Sea Region',
'Acharamz',
'Aeredus',
'Agi Bay Grotto',
'Anvil',
'Archad',
'Atrene',
'Beldaburo',
'Benirus Crypt',
'Bernd and Nessa Conina\'s Farmhouse',
'Blackfish Cave',
'Blue Raven: Hold',
'Brina Cross',
'Brine Stone: Cabin',
'Brine Stone: Hold',
'Broken Shrine Grotto',
'Charach',
'Conomorus Crypt',
'Corcaran Aster: Cabin',
'Corcaran Aster: Lower Hold',
'Corcaran Aster: Upper Hold',
'Crow Hall Cave',
'Crypsis: Cabin',
'Crypsis: Hold',
'Dasek Marsh Region',
'Duskwatch Keep',
'Ebonheart',
'Elendroth\'s Shack',
'Eumaeus',
'Felcius Farm',
'Fort Heath',
'Fort Telodrach',
'Fortyd Barrow',
'Garlas Agea',
'Ghost of Massiquera: Cabin',
'Ghost of Massiquera: Hold',
'Gilded Hills Region',
'Glisterpike',
'Gold Coast Region',
'Goldstone',
'Gosha Inn',
'Hal Sadek',
'Harkisius Barrow',
'Hearthrend: Cabin',
'Hearthrend: Hold',
'Heat Lightning',
'Karrel: Hold',
'Kingfisher Cave',
'Kyro Gavus\' Farmhouse',
'Marav',
'Melestrata',
'Merax Farm',
'Mischarstette',
'Mykoi Lighthouse',
'Nagaiarelle',
'None',
'Norinia',
'Ogima',
'Old Thraswatch',
'Olive Ridley: Cabin',
'Olive Ridley: Hold',
'Ossius Ranch',
'Pale Bay Cave',
'Pelelius Crypt',
'Pyraeus',
'Relds Farm',
'Sabina Silvian\'s Farmhouse',
'Salinen',
'Salthearth',
'Salvage Mine',
'Sinalon',
'Siralius Crypt',
'Sorhuk',
'Stirk Isle Region',
'Stonehead Cave',
'Sutch-Anvil Tollhouse',
'Swordmoth Legion Fort',
'Talgiana Crypt',
'Talgiana Orchard',
'TEM Brinerunner',
'TEM Eye of the Abecean: Cabin',
'TEM Eye of the Abecean: Hold',
'TEM Kintyra\'s Shield: Cabin',
'TEM Kintyra\'s Shield: Hold',
'TEM Parhelion: Cabin',
'TEM Parhelion: Flight Deck',
'TEM Parhelion: Hold',
'Thesigir Chasm',
'Thimistrel Crypt',
'Thresvy',
'Vallanytha Grotto',
'Valley of Diamonds',
'Valsar',
'Vilenkin',
'Vitta Barrow',
'Wavemoth Legion Fort',
'Wormusoel'
];

const SKYRIM_LOCATIONS = [
'Aejoir Cavern',
'Alovachtara',
'Alrasaide',
'Angturiel',
'Arianrha\'s Hut',
'Arsaig Cave',
'Bailcnoss',
'Bathmvall Barrow',
'Berfall Caverns',
'Bethorst',
'Bjagherd Cave',
'Black Teeth Caverns',
'Blackstone Silver Mine',
'Blood Paw Lodge',
'Braignainesaide',
'Briagmar Mine',
'Carvisa',
'Celera',
'Cranngin Camp',
'Criaglorc',
'Dagon Fel',
'Derech\'s Hut',
'Dragonstar',
'Dragonstar East',
'Dragonstar West',
'Druadach Highlands Region',
'Duibhmarad',
'Elgvring Cave',
'Even Odds Inn',
'Faldarach',
'Falkheim Region',
'Fort Vostangar',
'Fromnir\'s Cabin',
'Fyrignar',
'Galach\'s Hut',
'Gilded-Shield Manor',
'Gurmshal',
'Haimtir',
'Herlundsval Barrow',
'Hoarbeld',
'Hoota\'s Cabin',
'Hurfrid\'s Farm',
'Husteng Caverns',
'Hyyle\'s Hut',
'Iron-Mane Farm',
'Karthgad',
'Karthwasten',
'Karthwasten Caves',
'Kerlingroff Mine',
'Kolgath Hollow',
'Kulmar Cavern',
'Lorchwuir Heath Region',
'Mairager',
'Malagrok',
'Merduibh',
'Midkarth Region',
'Mirilstern',
'Nargozh Camp',
'Ocsenna',
'Orlund\'s Farmhouse',
'Ruari',
'Skjuggefald Deeps',
'Svaer',
'Taurus Hall',
'Uramok Camp',
'Vornberg',
'Vorndgad Forest Region',
'Vorngyd\'s Stand',
'Wilbur\'s House'
];

const SERVICES = [
'No_Services',
'BARTERS_WEAPONS',
'BARTERS_ARMOR',
'BARTERS_REPAIR_ITEMS',
'BARTERS_INGREDIENTS',
'BARTERS_ALCHEMY',
'BARTERS_BOOKS',
'BARTERS_CLOTHING',
'BARTERS_LIGHTS',
'BARTERS_MISC_ITEMS',
'BARTERS_LOCKPICKS',
'BARTERS_PROBES',
'BARTERS_APPARATUS',
'BARTERS_ENCHANTED_ITEMS',
'OFFERS_SPELLMAKING',
'OFFERS_SPELLS',
'OFFERS_REPAIRS',
'OFFERS_ENCHANTING',
'OFFERS_TRAINING',
'OFFERS_TRAVEL'
];

//DROP DOWN MENU CONSTANTS
const GROUPBY = ['Class', 'Faction', 'Race', 'Gender', 'Expansion', 'Location'];

const AGG_FUNCTION = ['AVG', 'SUM', 'MIN', 'MAX', 'COUNT'];

const LIMITS = ['10','25','50','100', '200'];

const SORTBY = ['Level',
'Gold',
'Health',
'Magicka',
'Fatigue',
'Hello',
'Fight',
'Flee',
'Alarm',
'Disposition',
'Reputation',
'Rank',
'Strength',
'Intelligence',
'Willpower',
'Agility',
'Speed',
'Endurance',
'Personality',
'Luck',
'Acrobatics',
'Alchemy',
'Alteration',
'Armorer',
'Athletics',
'Axe',
'Block',
'BluntWeapon',
'Conjuration',
'Destruction',
'Enchant',
'HandToHand',
'HeavyArmor',
'Illusion',
'LightArmor',
'LongBlade',
'Marksman',
'MediumArmor',
'Mercantile',
'Mysticism',
'Restoration',
'Security',
'ShortBlade',
'Sneak',
'Spear',
'Speechcraft',
'Unarmored'];

?>